### ISSUE TITLE
Long lines: plain text messages not reflowing when ThreadVis enabled

### ISSUE THREAD

**Issue by boolbag** [threadvis/ThreadVis#18]
Hi there!

Without ThreadVis, when you make a Read window smaller, the text of a text message reflows as the window gets smaller. 
With ThreadVis enabled, the text no longer reflows, so that long text lines extend past the window, and a horizontal scroll bar appears.

This problem does not seem to arise with html messages, only plain text:
One message with this problem I'm looking at right now has this header:
Content-Type: text/plain;
    charset="UTF-8"

I realize you haven't had a chance to spend much time on ThreadVis lateley, but thanks in advance for any insights.

**Comment by ahubmann** [comment]
Hm. I haven't noticed this behavior until now, but I'll see if I can reproduce it. Thanks for the report!

**Comment by SpokeNode** [comment]
Finding it hard to reproduce from scratch — don't know enough about email formats. I tried with random plain text messages, but the issue did not occur there.
On the other hand, when I forward a problematic message, the resulting message suffers from the same problem. If there was a way to forward a few lines of a message to you, you might be able to see it.

This issue was first brought to my attention by a friend who has a similar set-up. I've noticed it a few times but didn't start investigating was caused it until recently. The only way I've found to make it go away is to turn off ThreadVis, which is a shame. :)

**Comment by SpokeNode** [comment]
To give you an idea:

![threadvis-wrapping](https://cloud.githubusercontent.com/assets/7551671/7823497/fb3e4514-044f-11e5-8cf3-21164d18440f.png)

Some words are missing at the end of the line. If I keep shrinking, there is no further reflow (all the words on the right are cut off.)

**Comment by ahubmann** [comment]
Uh, never actually followed up on this. I'm still seeing this behavior in Thunderbird 102, albeit for _very_ narrow message windows. But yes, this only happens when ThreadVis is enabled. Seems the width of the visualization somehow stops Thunderbird from reflowing the message display.

**Comment by ahubmann** [comment]
Header injection has been rewritten for Thunderbird 115, if anyone is still seeing similar issues, please re-open this issue!
