### ISSUE TITLE
No message text in mouse over box

### ISSUE THREAD

**Issue by ErikKrause** [threadvis/ThreadVis#28]
The mouse over box on the message circles used to show the text of the message. Now it shows only "undefined". Header details are still shown. Thunderbird 60.7.2 on windows.

**Comment by ahubmann** [comment]
Hm. Working fine for me on TB 60.7.2, albeit on macOS. So "From", "Date" and "Subject" are correctly shown, but instead of the email body the tooltip shows "undefined"? Perhaps the email body in question was not (yet) loaded from the server, only the headers? If using IMAP, Thunderbird can be configured to keep only e.g. the most recent 30 days of emails as a local copy and fetch the other emails on demand (headers are always stored locally).

**Comment by ErikKrause** [comment]
The email body isn't even shown for the currently displayed message. Furthermore I set Thunderbird to download and keep all message bodies. Other things I tried to no avail:
- started Thunderbird with all other extensions disabled 
- reset all threadvis settings to defaults in about:config

Another thing I observed: body of mails that arrived in the current session show 'null'. After a Thunderbird restart they show 'undefined' like all other ones.

**Comment by ErikKrause** [comment]
I'm baffled. On my home PC it works. Same TB version, almost same extensions, same OS. I'd still be happy if it also worked an my work PC, and I'd be grateful for a hint what I could do. But if you like you could close this...

**Comment by antotamtam** [comment]
Similar problem here... except that Incoming messages are OK, only SENT messages are not previewed, showing just "undefined". It happens in all accounts, with different servers, except Gmail accounts which are working OK. Using IMAP mail in all accounts. Sending is always through Google SMTP server also for no-Gmail accounts, but anyway Sent mails are always correctly uploaded to IMAP server so this should be no problem, actually Threadvis used to work perfectly with this configuration.
Headers are shown OK in any case.
TB release 78.4, but this issue was present already some months ago, also in previous versions...
Any clue to solve it would be greatly appreciated!

**Comment by antotamtam** [comment]
![imagen](https://user-images.githubusercontent.com/49780376/98406930-17f01200-206f-11eb-8b17-5e1e2917bdb4.png)
Just an update to send an image of what is shown when hovering over a sent message: text preview missing, just "undefined".
ErikKrause did you get any workaround for this?

**Comment by ahubmann** [comment]
Following up on all open issues, even if it's been far too long: if you're still a ThreadVis user, is this still happening on the latest Thunderbird 102 with ThreadVis 3.4.2?
